apiVersion: v1
kind: Service
metadata:
  name: incident-management-service
spec:
  selector:
    app: incident-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer